server:
  port: 9900

spring:
  profiles:
    active: @profiles.active@
  application:
    name: database-view
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database-view?useUnicode=true&characterEncoding=UTF-8&autoConnect=true&rewriteBatchedStatements=true
    username: root
    password: jinzhaosn123